name: graduation_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  firebase_messaging: ^12.0.0
  email_validator: '2.0.1'
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - Images/

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/static/Cairo-Regular.ttf
          weight: 400
        - asset: fonts/Cairo/static/Cairo-Medium.ttf
          weight: 600
        - asset: fonts/Cairo/static/Cairo-Bold.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
